== Allgemeines
=== rechtliche Grundlagen
Seit dem 1. Juli 2008 ist das Bundesgesetz über Geoinformation (GeoIG, SR 510.62) <<allgemeines.adoc#doc-01,[1]>> in Kraft. Am 1. Juli 2012 erfolgte die vollständige Inkraftsetzung des kantonalen Geoinformationsgesetzes (kGeoiG, SRSZ 214.110) <<allgemeines.adoc#doc-03,[3]>>. Es hat zum Ziel, verbindliche Vorgaben für die Erfassung, Modellierung und den Austausch von Geodaten festzulegen. +

Am 1. Januar 2013 trat die kantonale Verordnung über Geoinformation (kGeoiV, SRSZ 214.111) <<allgemeines.adoc#doc-04,[4]>> in Kraft. Sie präzisiert das kGeoiG in fachlicher sowie technischer Hinsicht und führt im Anhang 1 den „Katalog der Geobasisdaten des Bundesrechts mit Zuständigkeit beim Kanton“ und im Anhang 2 den „Katalog der Geobasisdaten des kantonalen Rechts“. Darin werden die Fachstellen definiert, welche für die Ausarbeitung eines Geodatenmodells zuständig sind.

===  Zweck des Dokuments
Dieses Dokument beschreibt den Geobasisdatensatz
 
* *__forstliche Planung; Bereich Waldfunktion (Schutzwald) (A064)__.* +

__<weitere Beschreibungen>__ +

Diese Dokumentation richtet sich an alle Personen, welche sich über dieses Thema informieren möchten.

ifdef::backend-pdf[]
<<<
endif::[]
